import { apiFetch } from "./client";

export type Review = {
  id: number;
  swapId: number;
  reviewerId: number;
  reviewerUsername: string;
  reviewerName: string;
  rating: number;
  comment: string | null;
  autoGenerated: boolean;
  createdAt: string;
};

export type UserReviews = {
  userId: number;
  username: string;
  name: string;
  averageRating: number | null;
  reviewCount: number;
  reviews: Review[];
};

export function getUserReviews(token: string, userId: number): Promise<UserReviews> {
  return apiFetch<UserReviews>(`/api/users/${userId}/reviews`, {}, token);
}

export function submitReview(
  token: string,
  matchId: number,
  input: { rating?: number; comment?: string },
): Promise<Review> {
  return apiFetch<Review>(
    `/api/matches/${matchId}/review`,
    { method: "POST", body: JSON.stringify(input) },
    token,
  );
}
