import { apiFetch } from "./client";
import type { ClothingItem } from "./clothingItems";

export type SwapStatus = "PENDING" | "ACCEPTED" | "REJECTED";

export type Swap = {
  id: number;
  matchId: number;
  status: SwapStatus;
  iAccepted: boolean;
  otherAccepted: boolean;
  reviewed: boolean;
  myReviewRating: number | null;
  myReviewComment: string | null;
  myReviewAutoGenerated: boolean | null;
  updatedAt: string;
};

export function getSwap(token: string, matchId: number): Promise<Swap> {
  return apiFetch<Swap>(`/api/matches/${matchId}/swap`, {}, token);
}

export function acceptSwap(token: string, matchId: number): Promise<Swap> {
  return apiFetch<Swap>(`/api/matches/${matchId}/swap/accept`, { method: "PATCH" }, token);
}

export function rejectSwap(token: string, matchId: number): Promise<Swap> {
  return apiFetch<Swap>(`/api/matches/${matchId}/swap/reject`, { method: "PATCH" }, token);
}

export type SwapHistoryEntry = {
  matchId: number;
  otherUserId: number;
  otherUsername: string;
  otherUserName: string;
  otherUserProfilePictureUrl: string | null;
  myItem: ClothingItem;
  otherItem: ClothingItem;
  completedAt: string;
};

export function listSwapHistory(token: string): Promise<SwapHistoryEntry[]> {
  return apiFetch<SwapHistoryEntry[]>("/api/swaps/history", {}, token);
}
