"use client";

import { useEffect, useState } from "react";
import { useAuth } from "@/components/AuthProvider";
import { getUserReviews, type UserReviews as UserReviewsData } from "@/lib/api/reviews";

function Stars({ rating }: { rating: number }) {
  return (
    <span aria-label={`${rating} out of 5 stars`}>
      {"★".repeat(rating)}
      <span className="text-zinc-400 dark:text-zinc-600">{"★".repeat(5 - rating)}</span>
    </span>
  );
}

export function UserReviews({ userId, showIdentity = false }: { userId: number; showIdentity?: boolean }) {
  const { token } = useAuth();
  const [data, setData] = useState<UserReviewsData | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!token) {
      return;
    }
    // eslint-disable-next-line react-hooks/set-state-in-effect -- clearing stale data before refetching for a new userId, not a derived render value
    setData(null);
    setError(null);
    getUserReviews(token, userId)
      .then(setData)
      .catch(() => setError("Couldn't load reviews."));
  }, [token, userId]);

  if (error) {
    return <p className="text-sm text-red-600">{error}</p>;
  }
  if (!data) {
    return <p className="text-sm text-zinc-600 dark:text-zinc-400">Loading reviews…</p>;
  }

  return (
    <div className="flex flex-col gap-4">
      {showIdentity && (
        <div>
          <h1 className="text-xl font-semibold">{data.name}</h1>
          <p className="text-sm text-zinc-600 dark:text-zinc-400">@{data.username}</p>
        </div>
      )}

      <p className="text-sm">
        {data.averageRating === null ? (
          <span className="text-zinc-600 dark:text-zinc-400">No reviews yet.</span>
        ) : (
          <>
            <span className="font-medium">{data.averageRating.toFixed(1)} / 5</span>{" "}
            <span className="text-zinc-600 dark:text-zinc-400">
              average from {data.reviewCount} review{data.reviewCount === 1 ? "" : "s"}
            </span>
          </>
        )}
      </p>

      {data.reviews.length > 0 && (
        <ul className="flex flex-col gap-3">
          {data.reviews.map((review) => (
            <li key={review.id} className="rounded-lg border border-black/10 p-3 text-sm dark:border-white/20">
              <div className="flex items-center justify-between gap-2">
                <span className="text-amber-500 dark:text-amber-400">
                  <Stars rating={review.rating} />
                </span>
                <span className="text-xs text-zinc-600 dark:text-zinc-400">
                  {new Date(review.createdAt).toLocaleDateString()}
                </span>
              </div>
              <p className="mt-1 text-xs text-zinc-600 dark:text-zinc-400">from {review.reviewerName}</p>
              {review.comment && <p className="mt-2">{review.comment}</p>}
              {review.autoGenerated && (
                <p className="mt-2 text-xs text-zinc-500 dark:text-zinc-500">
                  No review was left — this is an automatic rating.
                </p>
              )}
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
