-- Initial schema. Flyway migrations are append-only: never edit this file
-- once it has run anywhere (AUDIT.md §7.6) -- add a new V2__... migration instead.
--
-- Design choices carried over from AUDIT.md §5/§10/§13:
--   * every relationship is a real FK, never a raw "Long that means an id"
--   * enums are enforced with CHECK constraints, not left as free-form strings
--   * the swipe/match/swap tables are shaped so match detection and swap
--     transitions can be single atomic statements, not client-side logic
--   * email activation is deliberately skipped for v1 (accounts are active on
--     registration) rather than left as a half-wired gate -- revisit if/when
--     real user signup (not just self-testing) is in scope.

CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE user_profile (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_user_id       BIGINT NOT NULL UNIQUE REFERENCES app_user (id) ON DELETE CASCADE,
    username          VARCHAR(50) NOT NULL UNIQUE,
    name              VARCHAR(255) NOT NULL,
    bio               TEXT,
    profile_picture_url TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE clothing_item (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_profile_id BIGINT NOT NULL REFERENCES user_profile (id) ON DELETE CASCADE,
    name                  VARCHAR(255) NOT NULL,
    image_url             TEXT NOT NULL,
    brand                 VARCHAR(255),
    item_type             VARCHAR(50) NOT NULL,
    description           TEXT,
    clothing_size         VARCHAR(10) NOT NULL
        CHECK (clothing_size IN ('XS', 'S', 'M', 'L', 'XL', 'XXL')),
    colour                VARCHAR(50),
    condition             VARCHAR(20) NOT NULL
        CHECK (condition IN ('NEW', 'LIKE_NEW', 'GOOD', 'FAIR', 'WORN')),
    gender                VARCHAR(20) NOT NULL
        CHECK (gender IN ('MENS', 'WOMENS', 'UNISEX', 'KIDS')),
    last_accessed         TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_clothing_item_owner ON clothing_item (owner_user_profile_id);
CREATE INDEX idx_clothing_item_last_accessed ON clothing_item (last_accessed DESC);

CREATE TABLE swipe (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    swiper_user_profile_id BIGINT NOT NULL REFERENCES user_profile (id) ON DELETE CASCADE,
    swiped_clothing_item_id BIGINT NOT NULL REFERENCES clothing_item (id) ON DELETE CASCADE,
    decision               VARCHAR(10) NOT NULL CHECK (decision IN ('LIKE', 'DISLIKE')),
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (swiper_user_profile_id, swiped_clothing_item_id)
);

-- A match pairs two users over one item each (the items each side offered).
-- Canonical ordering (user_a_profile_id < user_b_profile_id) means the
-- mutual-swipe check can look for exactly one row regardless of who
-- triggered the second swipe, and the app-level unique constraint prevents
-- the same pair matching twice.
CREATE TABLE item_match (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_a_profile_id  BIGINT NOT NULL REFERENCES user_profile (id) ON DELETE CASCADE,
    item_a_id          BIGINT NOT NULL REFERENCES clothing_item (id) ON DELETE CASCADE,
    user_b_profile_id  BIGINT NOT NULL REFERENCES user_profile (id) ON DELETE CASCADE,
    item_b_id          BIGINT NOT NULL REFERENCES clothing_item (id) ON DELETE CASCADE,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (user_a_profile_id < user_b_profile_id),
    UNIQUE (user_a_profile_id, item_a_id, user_b_profile_id, item_b_id)
);

-- One swap per match, real state transitions (PATCH .../accept, .../reject)
-- on this single row -- never a new row per AUDIT.md §7/§13.
CREATE TABLE swap (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id   BIGINT NOT NULL UNIQUE REFERENCES item_match (id) ON DELETE CASCADE,
    status     VARCHAR(20) NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE message (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id              BIGINT NOT NULL REFERENCES item_match (id) ON DELETE CASCADE,
    sender_user_profile_id BIGINT NOT NULL REFERENCES user_profile (id) ON DELETE CASCADE,
    content               TEXT NOT NULL,
    image_url             TEXT,
    sent_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    read_status           VARCHAR(10) NOT NULL DEFAULT 'SENT'
        CHECK (read_status IN ('SENT', 'DELIVERED', 'READ'))
);

CREATE INDEX idx_message_match_sent_at ON message (match_id, sent_at DESC);
