-- Reviews/ratings: one review per (swap, reviewer) -- each side of a completed
-- swap can leave exactly one review of the other, same "one row, real state"
-- shape as `swap` itself rather than an open-ended event log.
CREATE TABLE review (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    swap_id                   BIGINT NOT NULL REFERENCES swap (id) ON DELETE CASCADE,
    reviewer_user_profile_id  BIGINT NOT NULL REFERENCES user_profile (id) ON DELETE CASCADE,
    reviewee_user_profile_id  BIGINT NOT NULL REFERENCES user_profile (id) ON DELETE CASCADE,
    rating                    INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment                   VARCHAR(1000),
    auto_generated            BOOLEAN NOT NULL DEFAULT FALSE,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (swap_id, reviewer_user_profile_id)
);

CREATE INDEX idx_review_reviewee ON review (reviewee_user_profile_id);
