"use client";

import type { Client } from "@stomp/stompjs";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { useAuth } from "@/components/AuthProvider";
import { RatingBadge } from "@/components/RatingBadge";
import { ApiError } from "@/lib/api/client";
import { listMatches, type Match } from "@/lib/api/matches";
import { listMessages, sendMessage, type Message } from "@/lib/api/messages";
import { submitReview } from "@/lib/api/reviews";
import { acceptSwap, getSwap, rejectSwap, type Swap } from "@/lib/api/swaps";
import { connectMatchSocket } from "@/lib/ws/matchSocket";

export default function MatchThreadPage() {
  const { token, user, isLoading } = useAuth();
  const router = useRouter();
  const params = useParams<{ matchId: string }>();
  const matchId = Number(params.matchId);

  const [match, setMatch] = useState<Match | null>(null);
  const [messages, setMessages] = useState<Message[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [draft, setDraft] = useState("");
  const [connected, setConnected] = useState(false);
  const [isSending, setIsSending] = useState(false);
  const [swap, setSwap] = useState<Swap | null>(null);
  const [swapError, setSwapError] = useState<string | null>(null);
  const [isDeciding, setIsDeciding] = useState(false);

  const [isReviewFormOpen, setIsReviewFormOpen] = useState(false);
  const [reviewRating, setReviewRating] = useState<number | null>(null);
  const [reviewComment, setReviewComment] = useState("");
  const [isSubmittingReview, setIsSubmittingReview] = useState(false);
  const [reviewError, setReviewError] = useState<string | null>(null);
  // Only true for the moment right after "Item received" auto-submits --
  // switches the form's header copy back to the generic "Update your rating"
  // as soon as the user does anything else (edits, saves, or reopens later).
  const [justAutoReviewed, setJustAutoReviewed] = useState(false);

  const bottomRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (!isLoading && !user) {
      router.replace("/login");
    }
  }, [isLoading, user, router]);

  useEffect(() => {
    if (!token || Number.isNaN(matchId)) {
      return;
    }
    listMatches(token)
      .then((matches) => setMatch(matches.find((m) => m.id === matchId) ?? null))
      .catch(() => setError("Couldn't load this match."));
    listMessages(token, matchId)
      .then(setMessages)
      .catch(() => setError("Couldn't load messages."));
    getSwap(token, matchId)
      .then(setSwap)
      .catch(() => setSwapError("Couldn't load swap status."));
  }, [token, matchId]);

  useEffect(() => {
    if (!token || Number.isNaN(matchId)) {
      return;
    }
    let client: Client | null = connectMatchSocket({
      token,
      matchId,
      onMessage: (message) => setMessages((prev) => (prev ? [...prev, message] : [message])),
      onSwapUpdate: setSwap,
      onConnectedChange: setConnected,
    });
    return () => {
      client?.deactivate();
      client = null;
    };
  }, [token, matchId]);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ block: "end" });
  }, [messages]);

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const content = draft.trim();
    if (!token || !content || isSending) {
      return;
    }
    setIsSending(true);
    setError(null);
    try {
      await sendMessage(token, matchId, content);
      setDraft("");
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Couldn't send that message.");
    } finally {
      setIsSending(false);
    }
  }

  async function handleSwapDecision(decide: (token: string, matchId: number) => Promise<Swap>) {
    if (!token || isDeciding) {
      return;
    }
    setIsDeciding(true);
    setSwapError(null);
    try {
      setSwap(await decide(token, matchId));
    } catch (err) {
      setSwapError(err instanceof ApiError ? err.message : "Couldn't update the swap.");
    } finally {
      setIsDeciding(false);
    }
  }

  function applyReviewResult(result: { rating: number; comment: string | null; autoGenerated: boolean }) {
    setSwap((prev) =>
      prev
        ? {
            ...prev,
            reviewed: true,
            myReviewRating: result.rating,
            myReviewComment: result.comment,
            myReviewAutoGenerated: result.autoGenerated,
          }
        : prev,
    );
  }

  // Pressing "Item received" immediately records a default 5-star review --
  // the swap is "reviewed" the instant this call succeeds, so there's no
  // window where closing the tab (or anything else) could leave the button
  // reappearing later as if nothing had happened. The form then opens
  // pre-filled with that same 5-star default so the user can still give a
  // specific rating; submitting overwrites the auto-generated one in place.
  async function handleItemReceived() {
    if (!token || isSubmittingReview) {
      return;
    }
    setIsSubmittingReview(true);
    setReviewError(null);
    try {
      const result = await submitReview(token, matchId, {});
      applyReviewResult(result);
      setReviewRating(result.rating);
      setReviewComment(result.comment ?? "");
      setJustAutoReviewed(true);
      setIsReviewFormOpen(true);
    } catch (err) {
      setReviewError(err instanceof ApiError ? err.message : "Couldn't mark this item as received.");
    } finally {
      setIsSubmittingReview(false);
    }
  }

  function openReviewForm() {
    setReviewRating(swap?.myReviewRating ?? null);
    setReviewComment(swap?.myReviewComment ?? "");
    setReviewError(null);
    setJustAutoReviewed(false);
    setIsReviewFormOpen(true);
  }

  function closeReviewForm() {
    setIsReviewFormOpen(false);
    setJustAutoReviewed(false);
  }

  async function handleSubmitReview() {
    if (!token || isSubmittingReview) {
      return;
    }
    setIsSubmittingReview(true);
    setReviewError(null);
    try {
      const result = await submitReview(token, matchId, {
        rating: reviewRating ?? undefined,
        comment: reviewComment.trim() || undefined,
      });
      applyReviewResult(result);
      closeReviewForm();
    } catch (err) {
      setReviewError(err instanceof ApiError ? err.message : "Couldn't submit your review.");
    } finally {
      setIsSubmittingReview(false);
    }
  }

  if (isLoading || !user) {
    return (
      <div className="flex flex-1 items-center justify-center">
        <p className="text-sm text-zinc-600 dark:text-zinc-400">Loading…</p>
      </div>
    );
  }

  return (
    <div className="mx-auto flex w-full max-w-2xl flex-1 flex-col gap-4 px-4 py-6">
      <div className="flex items-center justify-between border-b border-black/10 pb-3 dark:border-white/20">
        <button type="button" onClick={() => router.back()} className="text-sm underline">
          ← Back
        </button>
        {match && (
          <div className="text-right text-sm font-medium">
            <p>
              <Link href={`/matches/${matchId}/user`} className="underline">
                {match.otherUserName}
              </Link>{" "}
              · {match.myItem.name} for {match.otherItem.name}
            </p>
            <RatingBadge
              userId={match.otherUserId}
              averageRating={match.otherUserAverageRating}
              reviewCount={match.otherUserReviewCount}
              className="justify-end font-normal"
            />
          </div>
        )}
      </div>

      {match && swap && (
        <div className="rounded-lg border border-black/10 p-3 text-sm dark:border-white/20">
          {swap.status === "ACCEPTED" && (
            <div className="flex flex-col gap-3">
              <p className="font-medium text-green-700 dark:text-green-400">
                Swap complete — {match.myItem.name} and {match.otherItem.name} are no longer up for grabs.
              </p>

              {!isReviewFormOpen && !swap.reviewed && (
                <button
                  type="button"
                  onClick={handleItemReceived}
                  disabled={isSubmittingReview}
                  className="self-start rounded bg-foreground px-3 py-1.5 text-xs text-background disabled:opacity-50"
                >
                  {isSubmittingReview ? "Marking as received…" : "Item received"}
                </button>
              )}
              {!isReviewFormOpen && !swap.reviewed && reviewError && (
                <p className="text-sm text-red-600">{reviewError}</p>
              )}

              {!isReviewFormOpen && swap.reviewed && (
                <div className="flex flex-col gap-1">
                  <p>
                    You rated {match.otherUserName}{" "}
                    <span className="text-amber-500 dark:text-amber-400" aria-hidden="true">
                      {"★".repeat(swap.myReviewRating ?? 5)}
                      <span className="text-zinc-400 dark:text-zinc-600">
                        {"★".repeat(5 - (swap.myReviewRating ?? 5))}
                      </span>
                    </span>
                  </p>
                  {swap.myReviewComment && <p className="text-zinc-600 dark:text-zinc-400">“{swap.myReviewComment}”</p>}
                  {swap.myReviewAutoGenerated && (
                    <p className="text-xs text-zinc-500 dark:text-zinc-500">
                      No review was left — this was an automatic rating.
                    </p>
                  )}
                  <button type="button" onClick={openReviewForm} className="self-start text-xs underline">
                    Edit review
                  </button>
                </div>
              )}

              {isReviewFormOpen && (
                <div className="flex flex-col gap-2 rounded border border-black/10 p-3 dark:border-white/20">
                  <p className="text-sm">
                    {justAutoReviewed
                      ? `${match.otherUserName} was automatically given 5 stars. Want to set a specific rating instead?`
                      : `Update your rating for ${match.otherUserName}`}
                  </p>
                  <div className="flex gap-1 text-xl">
                    {[1, 2, 3, 4, 5].map((value) => (
                      <button
                        key={value}
                        type="button"
                        onClick={() => setReviewRating(value)}
                        aria-label={`Rate ${value} star${value === 1 ? "" : "s"}`}
                        className={value <= (reviewRating ?? 0) ? "text-amber-500" : "text-zinc-400 dark:text-zinc-600"}
                      >
                        ★
                      </button>
                    ))}
                  </div>
                  <textarea
                    rows={2}
                    maxLength={1000}
                    value={reviewComment}
                    onChange={(event) => setReviewComment(event.target.value)}
                    placeholder="Say a little about why (optional)"
                    className="rounded border border-black/10 px-3 py-2 text-sm dark:border-white/20"
                  />
                  {reviewError && <p className="text-sm text-red-600">{reviewError}</p>}
                  <div className="flex flex-wrap items-center gap-3">
                    <button
                      type="button"
                      onClick={handleSubmitReview}
                      disabled={isSubmittingReview || reviewRating === null}
                      className="rounded bg-foreground px-3 py-1.5 text-xs text-background disabled:opacity-50"
                    >
                      Save
                    </button>
                    <button
                      type="button"
                      onClick={closeReviewForm}
                      disabled={isSubmittingReview}
                      className="rounded border border-black/10 px-3 py-1.5 text-xs disabled:opacity-50 dark:border-white/20"
                    >
                      {justAutoReviewed ? "Keep 5 stars" : "Cancel"}
                    </button>
                  </div>
                </div>
              )}
            </div>
          )}
          {swap.status === "REJECTED" && (
            <p className="text-zinc-600 dark:text-zinc-400">This swap was declined.</p>
          )}
          {swap.status === "PENDING" && (
            <div className="flex items-center justify-between gap-3">
              <p>
                {swap.iAccepted
                  ? `You accepted. Waiting for ${match.otherUserName} to confirm.`
                  : swap.otherAccepted
                    ? `${match.otherUserName} wants to complete this swap.`
                    : `Ready to swap ${match.myItem.name} for ${match.otherItem.name}?`}
              </p>
              <div className="flex shrink-0 gap-2">
                {!swap.iAccepted && (
                  <button
                    type="button"
                    onClick={() => handleSwapDecision(acceptSwap)}
                    disabled={isDeciding}
                    className="rounded bg-foreground px-3 py-1.5 text-xs text-background disabled:opacity-50"
                  >
                    Accept
                  </button>
                )}
                <button
                  type="button"
                  onClick={() => handleSwapDecision(rejectSwap)}
                  disabled={isDeciding}
                  className="rounded border border-black/10 px-3 py-1.5 text-xs disabled:opacity-50 dark:border-white/20"
                >
                  Reject
                </button>
              </div>
            </div>
          )}
        </div>
      )}
      {swapError && <p className="text-sm text-red-600">{swapError}</p>}

      {error && <p className="text-sm text-red-600">{error}</p>}
      {messages === null && !error && (
        <p className="text-sm text-zinc-600 dark:text-zinc-400">Loading messages…</p>
      )}
      {messages && messages.length === 0 && (
        <p className="text-sm text-zinc-600 dark:text-zinc-400">
          No messages yet. Say hello!
        </p>
      )}

      <div className="flex flex-1 flex-col gap-2">
        {messages?.map((message) => {
          const mine = message.senderId === user.id;
          return (
            <div key={message.id} className={`flex ${mine ? "justify-end" : "justify-start"}`}>
              <p
                className={`max-w-[75%] rounded-lg px-3 py-2 text-sm ${
                  mine
                    ? "bg-foreground text-background"
                    : "bg-zinc-100 dark:bg-zinc-900"
                }`}
              >
                {message.content}
              </p>
            </div>
          );
        })}
        <div ref={bottomRef} />
      </div>

      <form onSubmit={handleSubmit} className="flex gap-2 border-t border-black/10 pt-3 dark:border-white/20">
        <input
          value={draft}
          onChange={(event) => setDraft(event.target.value)}
          placeholder={connected ? "Type a message…" : "Connecting…"}
          disabled={!connected || isSending}
          className="flex-1 rounded border border-black/10 px-3 py-2 text-sm disabled:opacity-50 dark:border-white/20"
        />
        <button
          type="submit"
          disabled={!connected || isSending || !draft.trim()}
          className="rounded bg-foreground px-4 py-2 text-sm text-background disabled:opacity-50"
        >
          Send
        </button>
      </form>
    </div>
  );
}
