package com.threadtrades.review;

import java.time.Instant;

public record ReviewResponse(
        Long id,
        Long swapId,
        Long reviewerId,
        String reviewerUsername,
        String reviewerName,
        int rating,
        String comment,
        boolean autoGenerated,
        Instant createdAt) {

    static ReviewResponse from(Review review) {
        return new ReviewResponse(
                review.getId(),
                review.getSwap().getId(),
                review.getReviewer().getId(),
                review.getReviewer().getUsername(),
                review.getReviewer().getName(),
                review.getRating(),
                review.getComment(),
                review.isAutoGenerated(),
                review.getCreatedAt());
    }
}
