package com.threadtrades.review;

import com.threadtrades.swap.Swap;
import com.threadtrades.user.UserProfile;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.time.Instant;
import org.hibernate.annotations.CreationTimestamp;

/**
 * One review per (swap, reviewer) -- each side of a completed swap has exactly
 * one review row for it, same "single row of real state" shape as {@link Swap}.
 * Submitting again updates this same row (see {@link #update}) rather than
 * being rejected, so a reviewer can revise their rating/comment later.
 */
@Entity
@Table(name = "review")
public class Review {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "swap_id", nullable = false)
    private Swap swap;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "reviewer_user_profile_id", nullable = false)
    private UserProfile reviewer;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "reviewee_user_profile_id", nullable = false)
    private UserProfile reviewee;

    @Column(nullable = false)
    private int rating;

    @Column
    private String comment;

    @Column(name = "auto_generated", nullable = false)
    private boolean autoGenerated;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    protected Review() {
    }

    public Review(Swap swap, UserProfile reviewer, UserProfile reviewee, int rating, String comment, boolean autoGenerated) {
        this.swap = swap;
        this.reviewer = reviewer;
        this.reviewee = reviewee;
        this.rating = rating;
        this.comment = comment;
        this.autoGenerated = autoGenerated;
    }

    public Long getId() {
        return id;
    }

    public Swap getSwap() {
        return swap;
    }

    public UserProfile getReviewer() {
        return reviewer;
    }

    public UserProfile getReviewee() {
        return reviewee;
    }

    public int getRating() {
        return rating;
    }

    public String getComment() {
        return comment;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void update(int rating, String comment, boolean autoGenerated) {
        this.rating = rating;
        this.comment = comment;
        this.autoGenerated = autoGenerated;
    }
}
